services:
  - type: web
    name: adewale-oladiti-portfolio
    runtime: static
    region: frankfurt
    buildCommand: npm install && npm run build
    staticPublishPath: ./out
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
